apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aks-demo
  template:
    metadata:
      labels:
        app: aks-demo
    spec:
      containers:
      - name: aks-demo
        image: joaquimcosta/aks-demo:v1
        ports:
        - name: webserver
          containerPort: 8080
